### ISSUE TITLE
Issue with LiquidFilter

### ISSUE THREAD

**Issue by couet** [gemfarmer/jekyll-liquify#8]
Since a few days I get this error message when running the command `bundle exec jekyll serve --baseurl="/base"` :

```
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/3.1.0/bin/jekyll)
/usr/local/lib/ruby/gems/3.1.0/gems/jekyll-liquify-0.0.3/lib/jekyll-liquify.rb:15:in `<top (required)>': uninitialized constant LiquidFilter (NameError)

Liquid::Template.register_filter(LiquidFilter)
                                 ^^^^^^^^^^^^

```
and the web site stops building.

Do you know what it could be ?

**Comment by couet** [comment]
We forced  a lower version in order to resurrect our website:
https://github.com/root-project/web/pull/932
Is there a big in 0.0.3 ?

**Comment by jonsage** [comment]
I'm having this same issue

**Comment by glenrobson** [comment]
We also had the same issue:

```
/home/runner/work/website/website/vendor/bundle/ruby/3.1.0/gems/jekyll-liquify-0.0.3/lib/jekyll-liquify.rb:15:in `<top (required)>': uninitialized constant LiquidFilter (NameError)

Liquid::Template.register_filter(LiquidFilter)
                                 ^^^^^^^^^^^^
	from /home/runner/work/website/website/vendor/bundle/ruby/3.1.0/gems/jekyll-4.1.1/lib/jekyll/external.rb:60:in `require'
```

in [build](https://github.com/IIIF/website/actions/runs/7054794333/job/19204227953) and had to downgrade to 0.0.2.

**Comment by couet** [comment]
@gemfarmer : Is there a fix foreseen?

**Comment by yasulab** [comment]
I have investigated this issue and found that [this commit](https://github.com/gemfarmer/jekyll-liquify/commit/05dd00e51af26c2839138417a602f8a5bfa26cbc#diff-2da371b2f3c436b50121fafb061ec2a3e963272476a1a6596fbb9210e90ccfd4R4) changed [Liquid Filter](https://jekyllrb.com/docs/plugins/filters/) plugin's name from:

```diff
- LiquidFilter
+ LiquifyFilter
```

But `lib/jekyll-liquify.rb` still refers to outdated `LiquidFilter` module.
https://github.com/gemfarmer/jekyll-liquify/blob/9ab75afb83c2bc954eb790e7ea16e1e57d867dde/lib/jekyll-liquify.rb#L15

So updating the module name above would fix this issue.

UPDATE: Sent a pull request for this https://github.com/gemfarmer/jekyll-liquify/pull/9

**Comment by kigster** [comment]
Also fixed in #10
